lib/urls.py
# lib/urls.py

from django.urls import path
from . import views

app_name = 'lib'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('addBook/', views.addBook, name='addBook'),
    path('delBook/<int:book_id>', views.delBook, name='delBook'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from share.views import HomeView #视图里的对象

urlpatterns = [
    path('lib/', include('lib.urls')),#路径lib
    path('admin/', admin.site.urls),
    path('share/', include('share.urls')),
    #url(r'^admin/',include(admin.site.urls)),
]

share/urls.py
# share/urls.py

from django.urls import path
from . import views
from share.views import HomeView,DisplayView,MyView,SearchView #视图里的对象
from django.contrib import admin
from django.conf.urls import include,url

app_name = 'share'

urlpatterns = [
    #path('', views.index, name='index'),
    url(r'^$', HomeView.as_view(),name="home"), #引用视图对象需要调用对象的as.view().以对象的形式去调用，所以加括号
    url(r'^s/(?P<code>\d+)/$',DisplayView.as_view()),
    #/s/(?P<code>\d+ 使用了组匹配的方式 匹配code任意长度的数字，如/s/123456，将123456传给 DisplayView,这里的 code 必须和视图函数的 code 保持一致。
    url(r'^search/',SearchView.as_view(),name="search"),
    url(r'^my/$',MyView.as_view(),name="MY"),
]

lib/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

share/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Upload(models.Model):

    #访问该页面的次数 IntegerField 表示整数字段
    DownloadDocount = models.IntegerField(verbose_name=u"访问次数",default=0)

    #唯一标识一个文件 CharField 表示字符串字段
    code = models.CharField(max_length=8,verbose_name=u"code")

    #Datatime 表示文件上传的时间，其中datetime.now 不能加括号，否则时间就变成ORM生成的model的时间
    Datatime = models.DateTimeField(default=datetime.now,verbose_name=u"添加时间")

    #path 代表文件存储的路径
    path = models.CharField(max_length=32,verbose_name=u"下载路径")
    
    #文件名
    name = models.CharField(max_length=32,verbose_name=u"文件名",default="")
    
    #文件大小
    Filesize = models.CharField(max_length=10,verbose_name=u"文件大小")
    
    #上传文件的IP
    PCIP = models.CharField(max_length=32,verbose_name=u"IP地址",default="")
    
    class Meta():  #Meta用于定义数据表名，排序方式等
        verbose_name = "download"  #指明一个容易理解和表示的单词形式对象
        db_table = "download"      #声明数据表的名
    
    def __str__(self):  #表示在做查询操作时，我们看到的是 name 字段
        return self.name 

lib/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def index(request):
    return HttpResponse("Hello,world!")

def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list': book_list}
    return render(request, 'lib/detail.html', context)

def addBook(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']
    
    from django.utils import timezone
    temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
    temp_book.save()

    #重定向
    return HttpResponseRedirect(reverse('lib:detail'))

def delBook(request, book_id):
    bookID = book_id
    Book.objects.filter(id=bookID).delete()
    return HttpResponseRedirect(reverse('lib:detail'))

    

share/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Upload
from django.http import HttpResponsePermanentRedirect,HttpResponse
import random
import string
import datetime
import json
# Create your views here.


#def index(request):
#    return HttpResponse("Hello,world!")

class HomeView(View):
    def get(self,request): #get请求返回base.html
        return render(request,"base.html",{})


    def post(self, request):  # post请求
        if request.FILES:  # 如果有文件，向下执行，没有文件的情况,前端已经处理好。
            file = request.FILES.get("file")  # 获取文件
            name = file.name  # 获取文件名
            size = int(file.size)  # 获取文件大小
            with open('static/file/' + name, 'wb')as f:  # 写文件到static/files
                f.write(file.read())
            code = ''.join(random.sample(string.digits, 8))  # 生成随机八位的code
            u = Upload(
                path='static/file/' + name,
                name=name,
                Filesize=size,
                code=code,
                PCIP=str(request.META['REMOTE_ADDR']),  # 获取上传文件的用户ip
            )
            u.save()  # 存储数据库
            return HttpResponsePermanentRedirect("/share/s/" + code)
            # 使用 HttpResponsePermanentRedirect 重定向到展示文件的页面.这里的 code 唯一标示一个文件。

class DisplayView(View): #展示文件的视图类
    def get(self,request,code):  #支持get请求,并且可以接受一个参数，这里的 code 需要和 配置路由的code保持一致
        u = Upload.objects.filter(code=str(code)) #ORM 模型的查找
        if u: #如果u 有内容，u的访问次数+1.否则返回前端的内容为空
            for i in u :
                i.DownloadDocount +=1 #每次访问，访问次数+1
                i.save() #保存结果
        return render(request,'content.html',{"content":u}) #返回页面，其中content是 传给前端页面的内容
        
        #content.html在template文件夹中

class MyView(View): #用户管理类
    def get(self,request):
        IP = request.META['REMOTE_ADDR'] #获取用户IP
        u = Upload.objects.filter(PCIP=str(IP))  #查找数据
        for i in u:
            i.DownloadDocount +=1 #访问量
            i.save()
        return render(request,'content.html',{"content":u}) #返回数据给前端

class SearchView(View):
    def get(self,request):
        code = request.GET.get("kw") #获取请求中的kw值，即搜索内容
        u = Upload.objects.filter(name=str(code))
        data = {}
        if u :
            for i in  range(len(u)):
                u[i].DownloadDocount +=1
                u[i].save()
                data[i]={}
                data[i]['download'] = u[i].DownloadDocount
                data[i]['filename'] = u[i].name
                data[i]['id'] = u[i].id
                data[i]['ip'] = str(u[i].PCIP)
                data[i]['size'] = u[i].Filesize
                data[i]['time'] = str(u[i].Datatime.strftime('%Y-%m-%d %H:%M')) #格式化时间
                data[i]['key'] = u[i].code
        return HttpResponse(json.dumps(data),content_type="application/json")
        #使用 HttpResponse 返回的是 json  ，content_type是标准写法

lib/templates/lib/detail.html
/# lib/templates/detail.html/

<h1>Book List</h1>

<table>
    <tr>
        <td>书名</td>
        <td>作者</td>
        <td>出版社</td>
        <td>出版时间</td>
    </tr>
{% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'lib:delBook' book.id %}">删除</a></td>
    </tr>
{% endfor %}
</table>
<form action="{% url 'lib:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>书名：</span><input type="text" name="name"></p>
    <p><span>作者：</span><input type="text" name="author"></p>
    <p><span>出版社：</span><input type="text" name="pub_house"></p>
    <input type="submit" value="添加"">
</form>

share/templates/base.html

<!doctype html>
<html>
    <head>
        <meta content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="最好用的文件及时分享系统-by阿尔塞纳">
        <meta name="Keywords" content="文件及时分享,网盘,云盘">
        <title>我上传的文件 - 文件及时分享</title>
        <!-- Theme -->
        <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/static/css/animate.min.css" />
        <link rel="stylesheet" href="/static/css/vegas.min.css" />
        <link rel="stylesheet" href="/static/css/style.css" />
        <link rel="stylesheet" href="/static/css/style2.css" />
	<link rel="shortcut icon" href="/static/img/tz.ico" type="image/x-icon"/>
        <!-- Fonts -->
        <link rel="stylesheet" href="https://at.alicdn.com/t/font_xtmtjsdjlmc84cxr.css">
        <link rel="stylesheet" href="https://at.alicdn.com/t/font_k8psy17rqdoyldi.css">
</head>
<body>

    <div class="popup-window">
        <div id="shade">
            <div class="shade-container">
                <div class="stick stick-1"></div>
                <div class="stick stick-2"></div>
                <div class="stick stick-3"></div>
            </div>
            <div class="col-xs-12">
                <p class="text-info">testing</p>
            </div>
            <span id="ok">确定</span>
        </div>
    </div><!-- 遮罩层 -->
    <div class="page-loader"></div><!-- 循环进度条读取网页 -->
    <span id="h-animate" class="wow zoomInLeft" data-wow-delay="2s">&#10084;</span><!-- 开场 心 效果 -->
<!--===== Begin Header =====-->

<!--===== END Advertisement =====-->


<header>
    <div class="container">
        <div class="row">

            <div class="col-sm-6">
{#                <div class="logo wow bounceInDown" data-wow-delay="0.4s">#}
{#                    <a class="site-logo" href="/"></a>#}
{#                </div>#}
            </div>

            <div class="col-sm-6">
                <div class="logo-desc wow bounceInRight" data-wow-delay="0.4s">
            <a href="{% url 'share:MY' %}"><span class="logo-desc-text" href="/"><i class="iconfont">&#xe619;</i>Manage my files</span></a>
</div>
            </div>

        </div><!-- /.Row -->
    </div><!-- ./container -->
</header>
<!--===== END Header =====-->



<!--===== Begin Update File =====-->
<section id="content">
    <div class="container">

        <div class="col-sj-12">

            <!-- update-file-container -->
            <div class="up-container wow bounceIn" data-wow-delay="0.9s">

                <!-- search file -->
                <form id="search" action="{% url 'share:search' %}" method="get">
                    <div class="input-box">
                        <input id="files-info" name="kw" type="text" onkeydown="if(event.keyCode==13){return false;}" autocomplete="off" placeholder="Search File" />
                        <span class="iconfont search-text-icon">&#xe714;</span>
                    </div>
                </form><!-- END search file -->

                <!-- upload files -->
                <form id="form" action="/share/" method="post" runat="server" enctype="multipart/form-data">
                    <input id="files" name="file" multiple="multiple" style="display: none;" class="file-addr" type="file" />
                  {% csrf_token %}
                    <input id="bt" type="button" value="Upload File" />
                </form><!-- END Upload file -->


            </div>

            <!-- show_server_list -->
            <div class="show-file bounceIn">
                <div class="file-title">
                    <div class="file-name1" style="width:25%;">FileName</div>
                    <div class="file-size" style="width:10%;">FileSize</div>
                    <div class="file-size" style="width:10%;">Visits</div>
                    <div class="file-date" style="width:20%;">FileDate</div>
                    <div class="file-link" style="width:35%;">FileLink</div>
                </div>
                {% block content %}
                {% endblock %}
            </div>

        </div>

    </div><!-- /.container -->
</section>


<section>
    <div class="container">
        <div class="row">

            <div class="col-md-12 col-xs-12">
            </div>

        </div><!-- /.row -->
    </div>
</section>

<section>
    <div class="container">
        <div class="row">

            <div class="col-xs-12">
                <h1 class="wow fadeInUp" data-wow-delay="0.4s"><span>About</span> The Desc...</h1>
                <p class="about-text wow slideInLeft">1. Upload the file size is not more than 5M</p>
                <p class="about-text wow slideInLeft">2. Please properly keep network backup link</p>
            </div>

        </div><!-- /.row -->
    </div>
</section>



    <!-- ThemePlug -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/vegas.min.js"></script>
    <script src="/static/js/wow.min.js"></script>
    <script src="/static/js/dist/clipboard.min.js"></script>

    <!-- Page -->
    <script src="/static/js/index.js"></script>


</body>
</html>

share/templates/content.html
{% extends "base.html" %}  #使用extends 指定继承 base.html页面，
#用下面的内容去动态填充 base.html 里的content
{% block content %} #content 是后台传过来的值
    {% for i in content %}
                    <div class="file-content">
                    <div class="file-name" style="width:25%;">{{ i.name }}</div>
                    <div class="file-size" style="width:10%;">{{ i.Filesize }}B</div>
		    <div class="file-date" style="width:10%;">{{ i.DownloadDocount }}</div>
                    <div class="file-date" style="width:20%;">{{ i.Datatime }}</div>
                    <div class="file-link" style="width:35%; padding-right: 80px; text-overflow: ellipsis; overflow: hidden;">
                        <span>
                            http://192.168.133.135:9000/share/s/{{ i.code}}
                        </span>
                    </div>
                    <a href="/{{ i.path }}" style="color:#FFF;"><button>Download</button></a>
                    #实现下载文件
                </div>
    {% endfor %}
{% endblock %}